### ISSUE TITLE
Button shadow visible when button is hidden

### ISSUE THREAD

**Issue by gkopel** [burczyk/KBRoundedButton#2]
Hi,
Thanks for a great utility.
I think I've found a small issue however: button shadow is still visible if button is hidden.

I think it's enough to override setHidden: 

/**
 * Hides button together with it's shadow
 */
- (void)setHidden:(BOOL)hidden {
    [super setHidden:hidden];
    if (_shadowEnabled) {
        if (hidden) {
            [self removeBottomShadow];
        } else {
            [self addBottomShadow];
        }
    }
}

Kind regards,
Greg.

**Comment by burczyk** [comment]
Thank you for pointing this out and providing solution. It was included in new version and pushed to both repo and cocoa pods. Thanks!
